# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-11"

    config.vm.define "bolmos-oS" do |server|
        server.vm.hostname = "bolmos-oS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |vb|
            vb.name = "bolmos-oS"
            vb.memory = 1024
            vb.cpus = 1  
        end
        server.vm.provision "shell", inline: <<-SHELL
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip 192.168.56.110" K3S_KUBECONFIG_MODE="644" sh -
            sudo kubectl create -f /vagrant/confs
        SHELL
    end
end
