# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/alpine312"
    config.vm.synced_folder "apps/", "/home/apps", create: true
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "bolmos-oS" do |server|
        server.vm.hostname = "bolmos-oS"
        server.vm.network "private_network", ip: "192.168.42.110"
        server.vm.provider "virtualbox" do |vb|
            vb.name = "bolmos-oS"
            vb.memory = 1024
            vb.cpus = 1  
        end
        server.vm.provision "shell", inline: <<-SHELL
            sudo apk add -y curl vim
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip 192.168.42.110" K3S_KUBECONFIG_MODE="644" sh -
            sleep 10
            sudo kubectl create -f /home/apps
        SHELL
    end
end
