# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder "shared/", "/shared", create: true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "bolmos-oS" do |server|
    server.vm.hostname = "bolmos-oS"
    server.vm.network "private_network", ip: "192.168.42.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "bolmos-oS"
      vb.memory = 512
      vb.cpus = 1  
    end
    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip 192.168.42.110" K3S_KUBECONFIG_MODE="644" sh -
      cp /var/lib/rancher/k3s/server/node-token /shared/ 
    SHELL
  end

  config.vm.define "bolmos-oSW" do |serverWorker|
    serverWorker.vm.hostname = "bolmos-oSW"
    serverWorker.vm.network "private_network", ip: "192.168.42.111"
    serverWorker.vm.provider "virtualbox" do |vb|
      vb.name = "bolmos-oSW"
      vb.memory = 512
      vb.cpus = 1  
    end
    serverWorker.vm.provision "shell", inline: <<-SHELL
      while [ ! -f /shared/node-token ]; do
        sleep 2
      done
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip 192.168.42.111" K3S_URL=https://192.168.42.110:6443 K3S_TOKEN=$(cat /shared/node-token) sh -      
      rm /shared/node-token
    SHELL
  end
end
