# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.box_version = "202306.13.0"
  config.vm.boot_timeout = 600 

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
    vb.linked_clone = true
  end

  config.vm.define "bolmos-oS" do |server|
    server.vm.hostname = "bolmos-oS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "bolmos-oS"
    end
    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip 192.168.56.110" K3S_KUBECONFIG_MODE="644" sh -
      cp /var/lib/rancher/k3s/server/node-token /vagrant/ 
    SHELL
  end

  config.vm.define "bolmos-oSW" do |serverWorker|
    serverWorker.vm.hostname = "bolmos-oSW"
    serverWorker.vm.network "private_network", ip: "192.168.56.111"
    serverWorker.vm.provider "virtualbox" do |vb|
      vb.name = "bolmos-oSW"
    end
    serverWorker.vm.provision "shell", inline: <<-SHELL
      while [ ! -f /vagrant/node-token ]; do
        sleep 2
      done
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip 192.168.56.111" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/node-token) sh -      
      rm /vagrant/node-token
    SHELL
  end
end
