# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "bolmos-oS" do |server|
    server.vm.hostname = "bolmos-oS"
    server.vm.network "private_network", ip: "192.168.42.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "bolmos-oS"
      vb.memory = 512
      vb.cpus = 1  
    end
    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -
      cp /var/lib/rancher/k3s/server/node-token /vagrant/ 
    SHELL
  end

  config.vm.define "bolmos-oSW" do |serverWorker|
    serverWorker.vm.hostname = "bolmos-oSW"
    serverWorker.vm.network "private_network", ip: "192.168.42.111"
    serverWorker.vm.provider "virtualbox" do |vb|
      vb.name = "bolmos-oSW"
      vb.memory = 512
      vb.cpus = 1  
    end
    serverWorker.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.42.110 K3S_TOKEN=$(cat /vagrant/node-token) sh -      
    SHELL
  end
end
